version: 0.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  project: Simple-shell.sln
  verbosity: normal